apiVersion: iot.iot.example.com/v1alpha1
kind: EdgeNodeStatus
metadata:
  labels:
    app.kubernetes.io/name: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: edgenodestatus-sample
spec:
  # TODO(user): Add fields here
