# permissions for end users to view edgenodestatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edge-operator
    app.kubernetes.io/managed-by: kustomize
  name: edgenodestatus-viewer-role
rules:
- apiGroups:
  - iot.iot.example.com
  resources:
  - edgenodestatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iot.iot.example.com
  resources:
  - edgenodestatuses/status
  verbs:
  - get
