apiVersion: iot.iot.local/v1alpha1
kind: ReducedNodePolicy
metadata:
  labels:
    app.kubernetes.io/name: edge-operator-config
    app.kubernetes.io/managed-by: kustomize
  name: reducednodepolicy-sample
spec:
  # TODO(user): Add fields here
