# permissions for end users to edit reducednodepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edge-operator-config
    app.kubernetes.io/managed-by: kustomize
  name: reducednodepolicy-editor-role
rules:
- apiGroups:
  - iot.iot.local
  resources:
  - reducednodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot.local
  resources:
  - reducednodepolicies/status
  verbs:
  - get
